#:schema node_modules/wrangler/config-schema.json
# wrangler.toml
name = 'sublink'
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "948d59da42e34a889f97620df4d6f2c4" }
]

[assets]
directory = "./public"
